server:
  port: 2001

spring:
  application:
    name: maple_config
  cloud:
    config:
      profile: dev
      server:
        git:
          uri: https://github.com/hack-feng/maple-properties
          search-paths: /
      label: master


eureka:
  client:
    service-url:
      defaultZone: http://eureka1:1111/eureka/